export default class CommandLocalizations {
  static readonly LOOKING_FOR_TEAM_DESCRIPTION = {
    "en-US": "Looking For Team Commands",
    "en-GB": "Looking For Team Commands",
    bg: "Команди за търсене на екип",
    "zh-CN": "查找团队命令",
    "zh-TW": "尋找團隊命令",
    hr: "Naredbe za traženje tima",
    cs: "Příkazy pro hledání týmu",
    da: "Kommandoer til at finde et hold",
    nl: "Opdrachten voor het zoeken naar een team",
    fi: "Hakukomentoja",
    fr: "Commandes de recherche d'équipe",
    de: "Befehle zum Finden eines Teams",
    el: "Εντολές για την εύρεση μιας ομάδας",
    hi: "टीम ढूंढने के लिए आदेश",
    hu: "Csapatkeresési parancsok",
    it: "Comandi per la ricerca di un team",
    ja: "チームを探すコマンド",
    ko: "팀 찾기 명령어",
    lt: "Komandos, skirtos ieškoti komandos",
    no: "Kommandoer for å finne et lag",
    pl: "Polecenia wyszukiwania drużyny",
    "pt-BR": "Comandos de busca de equipe",
    ro: "Comenzi pentru a găsi o echipă",
    ru: "Команды поиска команды",
    "es-ES": "Comandos de búsqueda de equipo",
    "sv-SE": "Kommandon för att hitta ett lag",
    th: "คำสั่งการค้นหาทีม",
    tr: "Takım arama komutları",
    uk: "Команди для пошуку команди",
  };

  static readonly LOOKING_FOR_TEAM_GAME_VERSION_DESCRIPTION = {
    "en-US": "Game Version",
    "en-GB": "Game Version",
    bg: "Версия на играта",
    "zh-CN": "游戏版本",
    "zh-TW": "遊戲版本",
    hr: "Verzija igre",
    cs: "Verze hry",
    da: "Spilversion",
    nl: "Spelversie",
    fi: "Pelin versio",
    fr: "Version du jeu",
    de: "Spielversion",
    el: "Έκδοση παιχνιδιού",
    hi: "खेल संस्करण",
    hu: "Játékverzió",
    it: "Versione del gioco",
    ja: "ゲームバージョン",
    ko: "게임 버전",
    lt: "Žaidimo versija",
    no: "Spillversjon",
    pl: "Wersja gry",
    "pt-BR": "Versão do jogo",
    ro: "Versiunea jocului",
    ru: "Версия игры",
    "es-ES": "Versión del juego",
    "sv-SE": "Spelversion",
    th: "เวอร์ชันเกม",
    tr: "Oyun sürümü",
    uk: "Версія гри",
  };

  static readonly LOOKING_FOR_TEAM_PLATFORM_DESCRIPTION = {
    "en-US": "Which platform are you playing on?",
    "en-GB": "Which platform are you playing on?",
    bg: "На коя платформа играете?",
    "zh-CN": "你在哪个平台上玩？",
    "zh-TW": "你在哪個平台上玩？",
    hr: "Na kojoj platformi igraš?",
    cs: "Na které platformě hrajete?",
    da: "Hvilken platform spiller du på?",
    nl: "Op welk platform speel je?",
    fi: "Minkä alustan pelaat?",
    fr: "Sur quelle plate-forme jouez-vous?",
    de: "Auf welcher Plattform spielst du?",
    el: "Σε ποια πλατφόρμα παίζετε;",
    hi: "आप किस प्लेटफॉर्म पर खेल रहे हैं?",
    hu: "Melyik platformon játszol?",
    it: "Su quale piattaforma stai giocando?",
    ja: "どのプラットフォームでプレイしていますか？",
    ko: "어떤 플랫폼에서 게임을 하고 있습니까?",
    lt: "Kurioje platformoje žaidžiate?",
    no: "På hvilken plattform spiller du?",
    pl: "Na jakiej platformie grasz?",
    "pt-BR": "Em qual plataforma você está jogando?",
    ro: "Pe ce platformă jucați?",
    ru: "На какой платформе вы играете?",
    "es-ES": "¿En qué plataforma estás jugando?",
    "sv-SE": "På vilken plattform spelar du?",
    th: "คุณกำลังเล่นบนแพลตฟอร์มใด?",
    tr: "Hangi platformda oynuyorsun?",
    uk: "На якій платформі ви граєте?",
  };

  static readonly LOOKING_FOR_TEAM_DURATION_DESCRIPTION = {
    "en-US": "How long would you play (hours or minutes) numbers only?",
    "en-GB": "How long would you play (hours or minutes) numbers only?",
    bg: "Колко време ще играете (часове или минути) само числа?",
    "zh-CN": "你会玩多久（小时或分钟）只有数字？",
    "zh-TW": "你會玩多久（小時或分鐘）只有數字？",
    hr: "Koliko biste igrali (sati ili minute) samo brojevi?",
    cs: "Jak dlouho byste hráli (hodiny nebo minuty) pouze čísla?",
    da: "Hvor lang tid vil du spille (timer eller minutter) kun tal?",
    nl: "Hoe lang zou je spelen (uren of minuten) alleen nummers?",
    fi: "Kuinka kauan haluaisit pelata (tunteja tai minuutteja) vain numeroita?",
    fr: "Combien de temps voulez-vous jouer (heures ou minutes) uniquement des chiffres?",
    de: "Wie lange würdest du spielen (Stunden oder Minuten) nur Zahlen?",
    el: "Πόσο καιρό θα παίζατε (ώρες ή λεπτά) μόνο αριθμοί;",
    hi: "कितना समय आप खेलेंगे (घंटे या मिनट) केवल संख्या?",
    hu: "Mennyi ideig játszana (órák vagy perc) csak számok?",
    it: "Quanto tempo vorresti giocare (ore o minuti) solo numeri?",
    ja: "いくら時間を遊びますか（時間または分）数字のみ？",
    ko: "얼마나 오래 플레이하실 건가요 (시간 또는 분) 숫자만?",
    lt: "Kiek laiko norėtumėte žaisti (valandos arba minučių) tik skaičiai?",
    no: "Hvor lenge vil du spille (timer eller minutter) bare tall?",
    pl: "Ile czasu chciałbyś grać (godziny lub minuty) tylko liczby?",
    "pt-BR":
      "Quanto tempo você gostaria de jogar (horas ou minutos) apenas números?",
    ro: "Cât de mult ați dori să jucați (ore sau minute) doar numere?",
    ru: "Как долго вы бы играли (часы или минуты) только числа?",
    "es-ES": "¿Cuánto tiempo jugarías (horas o minutos) solo números?",
    "sv-SE": "Hur länge skulle du spela (timmar eller minuter) endast siffror?",
    th: "คุณจะเล่นเวลานานเท่าไหร่ (ชั่วโมงหรือนาที) เฉพาะตัวเลข?",
    tr: "Kaç saat oynayacaksınız (saat veya dakika) sadece sayılar?",
    uk: "Скільки часу ви б грали (години або хвилини) тільки числа?",
  };

  static readonly LOOKING_FOR_TEAM_ACTIVITY_DESCRIPTION = {
    "en-US": "What are you planning to do in Game?",
    "en-GB": "What are you planning to do in Game?",
    bg: "Какво планирате да направите в играта?",
    "zh-CN": "你打算在游戏中做什么？",
    "zh-TW": "你打算在遊戲中做什麼？",
    hr: "Što planirate učiniti u igri?",
    cs: "Co chcete v hře udělat?",
    da: "Hvad har du planlagt at gøre i spillet?",
    nl: "Wat ga je in het spel doen?",
    fi: "Mitä aiot tehdä pelissä?",
    fr: "Que comptez-vous faire dans le jeu?",
    de: "Was planst du im Spiel zu tun?",
    el: "Τι πρόκειται να κάνετε στο παιχνίδι;",
    hi: "आप खेल में क्या करने की योजना बना रहे हैं?",
    hu: "Mit tervezel tenni a játékban?",
    it: "Cosa stai pianificando di fare nel gioco?",
    ja: "ゲームで何をするつもりですか？",
    ko: "게임에서 무엇을 할 계획이십니까?",
    lt: "Ką planuojate daryti žaidime?",
    no: "Hva har du tenkt å gjøre i spillet?",
    pl: "Co zamierzasz zrobić w grze?",
    "pt-BR": "O que você planeja fazer no jogo?",
    ro: "Ce planuiți să faceți în joc?",
    ru: "Что вы планируете делать в игре?",
    "es-ES": "¿Qué planeas hacer en el juego?",
    "sv-SE": "Vad har du tänkt göra i spelet?",
    th: "คุณจะทำอะไรในเกม",
    tr: "Oyun içinde ne planlıyorsunuz?",
    uk: "Що ви плануєте робити в грі?",
  };

  static readonly LOOKING_FOR_TEAM_LOCATION_DESCRIPTION = {
    "en-US": "Where are you (System Name)?",
    "en-GB": "Where are you (System Name)?",
    bg: "Къде си (име на системата)?",
    "zh-CN": "你在哪里（系统名称）？",
    "zh-TW": "你在哪裡（系統名稱）？",
    hr: "Gdje si (naziv sustava)?",
    cs: "Kde jste (název systému)?",
    da: "Hvor er du (systemnavn)?",
    nl: "Waar ben je (systeemnaam)?",
    fi: "Missä olet (järjestelmän nimi)?",
    fr: "Où êtes-vous (nom du système)?",
    de: "Wo bist du (Systemname)?",
    el: "Που είσαι (όνομα συστήματος);",
    hi: "आप कहाँ हैं (सिस्टम नाम)?",
    hu: "Hol vagy (rendszer neve)?",
    it: "Dove sei (nome del sistema)?",
    ja: "どこにいますか（システム名）？",
    ko: "어디에 있습니까 (시스템 이름)?",
    lt: "Kur esate (sistemos pavadinimas)?",
    no: "Hvor er du (systemnavn)?",
    pl: "Gdzie jesteś (nazwa systemu)?",
    "pt-BR": "Onde você está (nome do sistema)?",
    ro: "Unde ești (numele sistemului)?",
    ru: "Где вы (название системы)?",
    "es-ES": "¿Dónde estás (nombre del sistema)?",
    "sv-SE": "Var är du (systemnamn)?",
    th: "คุณอยู่ที่ไหน (ชื่อระบบ)",
    tr: "Neredesin (Sistem Adı)?",
    uk: "Де ви (назва системи)?",
  };

  static readonly LOOKING_FOR_TEAM_SPOTS_DESCRIPTION = {
    "en-US": "How much space you have in your Team?",
    "en-GB": "How much space you have in your Team?",
    bg: "Колко място имате в екипа си?",
    "zh-CN": "你的团队有多少空间？",
    "zh-TW": "你的團隊有多少空間？",
    hr: "Koliko prostora imate u svom timu?",
    cs: "Kolikou kapacitu máte ve svém týmu?",
    da: "Hvor meget plads har du i dit hold?",
    nl: "Hoeveel ruimte heb je in je team?",
    fi: "Kuinka paljon tilaa sinulla on joukkueessasi?",
    fr: "Combien d'espace avez-vous dans votre équipe?",
    de: "Wie viel Platz haben Sie in Ihrem Team?",
    el: "Πόσο χώρο έχετε στην ομάδα σας;",
    hi: "आपके टीम में कितना स्थान है?",
    hu: "Mennyi hely van a csapatodban?",
    it: "Quanto spazio hai nel tuo Team?",
    ja: "あなたのチームにどれくらいのスペースがありますか？",
    ko: "팀에 얼마나 많은 공간이 있습니까?",
    lt: "Kiek vietos turite savo komandoje?",
    no: "Hvor mye plass har du i laget ditt?",
    pl: "Ile miejsca masz w swoim zespole?",
    "pt-BR": "Quanto espaço você tem em sua equipe?",
    ro: "Cât spațiu aveți în echipă?",
    ru: "Сколько места у вас в команде?",
    "es-ES": "¿Cuánto espacio tienes en tu equipo?",
    "sv-SE": "Hur mycket plats har du i ditt lag?",
    th: "คุณมีพื้นที่ในทีมของคุณมากน้อยแค่ไหน",
    tr: "Takımınızda ne kadar alan var?",
    uk: "Скільки місця у вас в команді?",
  };

  static readonly LOOKING_FOR_TEAM_HELP_DESCRIPTION = {
    "en-US": "Need help to use this BOT?",
    "en-GB": "Need help to use this BOT?",
    bg: "Нужда от помощ за използването на този BOT?",
    "zh-CN": "需要帮助使用此BOT吗？",
    "zh-TW": "需要幫助使用此BOT嗎？",
    hr: "Trebate pomoć za korištenje ovog BOT-a?",
    cs: "Potřebujete pomoc s použitím tohoto BOTu?",
    da: "Har brug for hjælp til at bruge denne BOT?",
    nl: "Heb je hulp nodig om deze BOT te gebruiken?",
    fi: "Tarvitsetko apua tämän BOTin käyttämiseen?",
    fr: "Besoin d'aide pour utiliser ce BOT?",
    de: "Benötigen Sie Hilfe, um diesen BOT zu verwenden?",
    el: "Χρειάζεστε βοήθεια για τη χρήση αυτού του BOT;",
    hi: "इस बॉट का उपयोग करने के लिए सहायता की आवश्यकता है?",
    hu: "Segítségre van szüksége ezen a BOT-on?",
    it: "Hai bisogno di aiuto per utilizzare questo BOT?",
    ja: "このBOTを使用するのに助けが必要ですか？",
    ko: "이 BOT을 사용하는 데 도움이 필요합니까?",
    lt: "Reikia pagalbos naudoti šį BOT?",
    no: "Trenger hjelp til å bruke denne BOT?",
    pl: "Potrzebujesz pomocy w użyciu tego BOT?",
    "pt-BR": "Precisa de ajuda para usar este BOT?",
    ro: "Ai nevoie de ajutor pentru a utiliza acest BOT?",
    ru: "Вам нужна помощь для использования этого BOT?",
    "es-ES": "¿Necesita ayuda para usar este BOT?",
    "sv-SE": "Behöver du hjälp att använda denna BOT?",
    th: "คุณต้องการความช่วยเหลือในการใช้ BOT นี้หรือไม่",
    tr: "Bu BOT'u kullanmak için yardıma mı ihtiyacınız var?",
    uk: "Вам потрібна допомога для використання цього BOT?",
  };

  static readonly LOOKING_FOR_TEAM_PING_DESCRIPTION = {
    "en-US": "Check if the Bot is up and Running",
    "en-GB": "Check if the Bot is up and Running",
    bg: "Проверете дали бота е включен и работи",
    "zh-CN": "检查机器人是否启动并运行",
    "zh-TW": "檢查機器人是否啟動並運行",
    hr: "Provjerite je li Bot uključen i pokrenut",
    cs: "Zkontrolujte, zda je Bot zapnutý a běží",
    da: "Tjek om Bot er tændt og kører",
    nl: "Controleer of de Bot aanstaat en draait",
    fi: "Tarkista, onko Bot käynnissä ja käynnissä",
    fr: "Vérifiez si le Bot est allumé et en marche",
    de: "Überprüfen Sie, ob der Bot eingeschaltet und aktiv ist",
    el: "Ελέγξτε αν το Bot είναι ενεργό και εκτελείται",
    hi: "बॉट को चेक करें कि यह चालू है और चल रहा है",
    hu: "Ellenőrizze, hogy a Bot be van kapcsolva és fut",
    it: "Controlla se il Bot è acceso e in esecuzione",
    ja: "Botがオンで実行されているかどうかを確認します",
    ko: "Bot이 켜져 있고 실행 중인지 확인하십시오",
    lt: "Patikrinkite, ar Bot yra įjungtas ir veikia",
    no: "Sjekk om Bot er på og kjører",
    pl: "Sprawdź, czy Bot jest włączony i działa",
    "pt-BR": "Verifique se o Bot está ligado e em execução",
    ro: "Verificați dacă Botul este pornit și funcționează",
    ru: "Проверьте, включен ли Bot и работает ли он",
    "es-ES": "Compruebe si el Bot está encendido y en ejecución",
    "sv-SE": "Kontrollera om Bot är på och kör",
    th: "ตรวจสอบว่า Bot ถูกเปิดใช้งานและกำลังทำงานอยู่หรือไม่",
    tr: "Bot'un açık ve çalışıyor olup olmadığını kontrol edin",
    uk: "Перевірте, чи увімкнено Bot і чи він працює",
  };

  static readonly LOOKING_FOR_TEAM_WHEN_DESCRIPTION = {
    "en-US": "How long from now you need to play, leave clear or 0 for now?",
    "en-GB": "How long from now you need to play, leave clear or 0 for now?",
    bg: "Колко време от сега трябва да играете, оставете ясно или 0 за сега?",
    "zh-CN": "从现在开始你需要多长时间来玩，清除或0？",
    "zh-TW": "從現在開始你需要多長時間來玩，清除或0？",
    hr: "Koliko dugo od sada trebate igrati, ostavite jasno ili 0 za sada?",
    cs: "Kolik času od nyní potřebujete hrát, nechte jasné nebo 0 pro nyní?",
    da: "Hvor lang tid fra nu skal du spille, forlade klart eller 0 nu?",
    nl: "Hoe lang vanaf nu moet je spelen, duidelijk achterlaten of 0 voor nu?",
    fi: "Kuinka kauan sinun on nyt pelaamista, jätä selkeästi tai 0 nyt?",
    fr: "Quand joueriez-vous à partir de maintenant (heures)",
    de: "Wie lange brauchen Sie ab jetzt, um zu spielen, klar zu lassen oder 0 für jetzt?",
    el: "Πόσο χρόνο από τώρα χρειάζεστε να παίξετε, αφήστε καθαρά ή 0 τώρα;",
    hi: "अब तक कितना समय खेलने की आपको आवश्यकता है, अब तक स्पष्ट छोड़ दें या 0?",
    hu: "Hány időtől most kell játszani, hagyja tiszta vagy 0 most?",
    it: "Quanto tempo da ora hai bisogno di giocare, lasciare chiaro o 0 per ora?",
    ja: "今からどれくらいの時間を遊ぶ必要がありますか、今は明確に残してください、または0ですか？",
    ko: "지금부터 얼마나 오래 플레이해야하는지 지금은 명확하게 또는 0으로 둘러싸십시오?",
    lt: "Kiek laiko nuo dabar jums reikia žaisti, palikti aiškiai arba 0 dabar?",
    no: "Hvor lenge fra nå må du spille, forlate klart eller 0 nå?",
    pl: "Ile czasu od teraz potrzebujesz grać, zostaw jasno lub 0 teraz?",
    "pt-BR":
      "Quanto tempo a partir de agora você precisa jogar, deixe claro ou 0 para agora?",
    ro: "Cât timp de la acum aveți nevoie să jucați, lăsați clar sau 0 acum?",
    ru: "Сколько времени сейчас вам нужно играть, оставить ясно или 0 сейчас?",
    "es-ES":
      "¿Cuánto tiempo desde ahora necesitas jugar, dejar claro o 0 para ahora?",
    "sv-SE": "Hur länge från nu måste du spela, lämna klart eller 0 nu?",
    th: "เวลาที่จะเล่นต้องใช้เวลาเท่าไหร่จากตอนนี้ ปล่อยให้ชัดเจนหรือ 0 ตอนนี้",
    tr: "Şimdi ne kadar süre oynamanız gerekiyor, şimdi açık bırakın veya 0?",
    uk: "Скільки часу з цього часу вам потрібно грати, залишити ясно або 0 зараз?",
  };

  static readonly SYTEM_FACTION_INFO_DESCRIPTION = {
    "en-US": "Get Systems Factions Info",
    "en-GB": "Get Systems Factions Info",
    bg: "Получаване на информация за фракциите на системите",
    "zh-CN": "获取系统势力信息",
    "zh-TW": "獲取系統勢力信息",
    hr: "Dobiti informacije o sustavima",
    cs: "Získat informace o systémech",
    da: "Få systemfaktionsoplysninger",
    nl: "Systeemfactie-informatie ophalen",
    fi: "Hanki järjestelmäfaktiotiedot",
    fr: "Obtenir des informations sur les factions du système",
    de: "Systemfraktionen-Informationen abrufen",
    el: "Λήψη πληροφοριών συστημάτων",
    hi: "सिस्टम फैक्शन जानकारी प्राप्त करें",
    hu: "Rendszer frakcióinak információinak lekérése",
    it: "Ottieni informazioni sulle fazioni del sistema",
    ja: "システムの情報を取得する",
    ko: "시스템 팩션 정보 가져 오기",
    lt: "Gauti sistemos frakcijų informaciją",
    no: "Få systemfaktainformasjon",
    pl: "Pobierz informacje o frakcjach systemu",
    "pt-BR": "Obter informações sobre facções do sistema",
    ro: "Obțineți informații despre facțiunile sistemului",
    ru: "Получить информацию о фракциях системы",
    "es-ES": "Obtener información sobre facciones del sistema",
    "sv-SE": "Hämta systemfraktioner information",
    th: "รับข้อมูลศัตรูพันธมิตรของระบบ",
    tr: "Sistem Faksiyon Bilgilerini Al",
    uk: "Отримати інформацію про фракції системи",
  };
  static readonly SYSTEM_TRAFFIC_INFO_DESCRIPTION = {
    "en-US": "Get Systems Traffic Info",
    "en-GB": "Get Systems Traffic Info",
    bg: "Получаване на информация за трафика на системите",
    "zh-CN": "获取系统流量信息",
    "zh-TW": "獲取系統流量信息",
    hr: "Dobiti informacije o prometu sustava",
    cs: "Získat informace o systému",
    da: "Få systemtrafikoplysninger",
    nl: "Systeemverkeersinformatie ophalen",
    fi: "Hanki järjestelmäliikenneinformaatio",
    fr: "Obtenir des informations sur le trafic du système",
    de: "Systemverkehrsinformationen abrufen",
    el: "Λήψη πληροφοριών κυκλοφορίας συστημάτων",
    hi: "सिस्टम ट्रैफिक जानकारी प्राप्त करें",
    hu: "Rendszerforgalom információinak lekérése",
    it: "Ottieni informazioni sul traffico del sistema",
    ja: "システムのトラフィック情報を取得する",
    ko: "시스템 트래픽 정보 가져 오기",
    lt: "Gauti sistemos eismo informaciją",
    no: "Få systemtrafikkinformasjon",
    pl: "Pobierz informacje o ruchu systemu",
    "pt-BR": "Obter informações sobre tráfego do sistema",
    ro: "Obțineți informații despre traficul sistemului",
    ru: "Получить информацию о трафике системы",
    "es-ES": "Obtener información sobre tráfico del sistema",
    "sv-SE": "Hämta systemtrafikinformation",
    th: "รับข้อมูลการจราจรของระบบ",
    tr: "Sistem Trafik Bilgilerini Al",
    uk: "Отримати інформацію про трафік системи",
  };

  static readonly SYSTEM_DEATH_INFO_DESCRIPTION = {
    "en-US": "Get Systems Death Info",
    "en-GB": "Get Systems Death Info",
    bg: "Получаване на информация за смъртта на системите",
    "zh-CN": "获取系统死亡信息",
    "zh-TW": "獲取系統死亡信息",
    hr: "Dobiti informacije o smrti sustava",
    cs: "Získat informace o smrti systému",
    da: "Få systemdødsoplysninger",
    nl: "Systeemdoodsinformatie ophalen",
    fi: "Hanki järjestelmäkuoleman tiedot",
    fr: "Obtenir des informations sur la mort du système",
    de: "Systemtodesinformationen abrufen",
    el: "Λήψη πληροφοριών θανάτου συστημάτων",
    hi: "सिस्टम मौत जानकारी प्राप्त करें",
    hu: "Rendszerhalál információinak lekérése",
    it: "Ottieni informazioni sulla morte del sistema",
    ja: "システムの死亡情報を取得する",
    ko: "시스템 사망 정보 가져 오기",
    lt: "Gauti sistemos mirties informaciją",
    no: "Få systemdødsinformasjon",
    pl: "Pobierz informacje o śmierci systemu",
    "pt-BR": "Obter informações sobre a morte do sistema",
    ro: "Obțineți informații despre moartea sistemului",
    ru: "Получить информацию о смерти системы",
    "es-ES": "Obtener información sobre la muerte del sistema",
    "sv-SE": "Hämta systemdödsinformation",
    th: "รับข้อมูลการตายของระบบ",
    tr: "Sistem Ölüm Bilgilerini Al",
    uk: "Отримати інформацію про смерть системи",
  };

  static readonly ELITE_SERVER_TICK_INFO_DESCRIPTION = {
    "en-US": "Get Elite Server Tick Info",
    "en-GB": "Get Elite Server Tick Info",
    bg: "Получаване на информация за тиковете на Elite Server",
    "zh-CN": "获取Elite Server Tick信息",
    "zh-TW": "獲取Elite Server Tick信息",
    hr: "Dobiti informacije o Elite Server Tick",
    cs: "Získat informace o Elite Server Tick",
    da: "Få Elite Server Tick-oplysninger",
    nl: "Elite Server Tick-informatie ophalen",
    fi: "Hanki Elite Server Tick-tiedot",
    fr: "Obtenir des informations sur Elite Server Tick",
    de: "Elite Server Tick-Informationen abrufen",
    el: "Λήψη πληροφοριών Elite Server Tick",
    hi: "एलाइट सर्वर टिक जानकारी प्राप्त करें",
    hu: "Elite Server Tick információinak lekérése",
    it: "Ottieni informazioni su Elite Server Tick",
    ja: "エリートサーバーチック情報を取得する",
    ko: "엘리트 서버 틱 정보 가져 오기",
    lt: "Gauti Elite Server Tick informaciją",
    no: "Få Elite Server Tick-informasjon",
    pl: "Pobierz informacje o Elite Server Tick",
    "pt-BR": "Obter informações sobre Elite Server Tick",
    ro: "Obțineți informații despre Elite Server Tick",
    ru: "Получить информацию о тике Elite Server",
    "es-ES": "Obtener información sobre Elite Server Tick",
    "sv-SE": "Hämta Elite Server Tick-information",
    th: "รับข้อมูล Elite Server Tick",
    tr: "Elite Server Tick Bilgilerini Al",
    uk: "Отримати інформацію про Elite Server Tick",
  };

  static readonly LOOKING_FOR_TEAM_GAME_MODE_DESCRIPTION = {
    "en-US": "Which game mode, Private Group or Open Play?",
    "en-GB": "Which game mode, Private Group or Open Play?",
    bg: "Кой режим на игра, частна група или отворена игра?",
    "zh-CN": "哪种游戏模式，私人组或开放游戏？",
    "zh-TW": "哪種遊戲模式，私人組或開放遊戲？",
    hr: "Koji je način igre, privatna grupa ili otvorena igra?",
    cs: "Jaký je režim hry, soukromá skupina nebo otevřená hra?",
    da: "Hvilken spillemåde, privat gruppe eller åben spil?",
    nl: "Welke spelmodus, privégroep of open spel?",
    fi: "Mikä on pelimuoto, yksityinen ryhmä tai avoin peli?",
    fr: "Quel mode de jeu, groupe privé ou jeu ouvert?",
    de: "Welcher Spielmodus, Private Gruppe oder Open Play?",
    el: "Ποια λειτουργία παιχνιδιού, ιδιωτική ομάδα ή ανοιχτή παιχνίδι?",
    hi: "खेल का कौन सा मोड, निजी समूह या खुला खेल?",
    hu: "Melyik játékmód, privát csoport vagy nyílt játék?",
    it: "Qual è la modalità di gioco, gruppo privato o gioco aperto?",
    ja: "どのゲームモード、プライベートグループまたはオープンプレイ？",
    ko: "어떤 게임 모드, 개인 그룹 또는 오픈 플레이?",
    lt: "Koks žaidimo režimas, privati grupė ar atvira žaidimo?",
    no: "Hvilken spillmodus, privat gruppe eller åpen spill?",
    pl: "Jaki jest tryb gry, prywatna grupa lub otwarta gra?",
    "pt-BR": "Qual é o modo de jogo, grupo privado ou jogo aberto?",
    ro: "Care este modul de joc, grup privat sau joc deschis?",
    ru: "Какой режим игры, частная группа или открытая игра?",
    "es-ES": "¿Cuál es el modo de juego, grupo privado o juego abierto?",
    "sv-SE": "Vilken spelmod, privat grupp eller öppet spel?",
    th: "โหมดเกมใด กลุ่มส่วนตัวหรือเล่นเปิด?",
    tr: "Hangi oyun modu, Özel Grup veya Açık Oynama?",
    uk: "Який режим гри, приватна група або відкрита гра?",
  };

  static readonly LOOKING_FOR_TEAM_EXTRA_DESCRIPTION = {
    "en-US": "Is there anything else you want to Add?",
    "en-GB": "Is there anything else you want to Add?",
    bg: "Има ли нещо друго, което искате да добавите?",
    "zh-CN": "还有什么你想添加的吗？",
    "zh-TW": "還有什麼你想添加的嗎？",
    hr: "Je li još nešto što želite dodati?",
    cs: "Ještě něco jiného, co chcete přidat?",
    da: "Er der noget andet, du vil tilføje?",
    nl: "Is er nog iets anders dat u wilt toevoegen?",
    fi: "Onko mitään muuta, mitä haluat lisätä?",
    fr: "Y a-t-il autre chose que vous voulez ajouter?",
    de: "Gibt es noch etwas anderes, das Sie hinzufügen möchten?",
    el: "Υπάρχει κάτι άλλο που θέλετε να προσθέσετε;",
    hi: "क्या आप अपने जोड़ने के लिए कुछ और चाहते हैं?",
    hu: "Van még valami, amit hozzá szeretne adni?",
    it: "C'è altro che vuoi aggiungere?",
    ja: "追加したいものはありますか？",
    ko: "추가하고 싶은 게 더 있습니까?",
    lt: "Ar yra dar ką nors, ką norite pridėti?",
    no: "Er det noe annet du vil legge til?",
    pl: "Czy jest jeszcze coś, co chcesz dodać?",
    "pt-BR": "Há algo mais que você queira adicionar?",
    ro: "Este ceva de adăugat?",
    ru: "Есть ли еще что-то, что вы хотите добавить?",
    "es-ES": "¿Hay algo más que quieras agregar?",
    "sv-SE": "Är det något annat du vill lägga till?",
    th: "มีอะไรอีกไหมที่คุณต้องการเพิ่ม?",
    tr: "Eklemek istediğiniz başka bir şey var mı?",
    uk: "Чи є ще щось, що ви хочете додати?",
  };

  static readonly COLONIZATION_BOT_DESCRIPTION = {
    "en-US": "Add Colonization Project",
    "en-GB": "Add Colonization Project",
    bg: "Добавяне на проект за колонизация",
    "zh-CN": "添加殖民化项目",
    "zh-TW": "添加殖民化項目",
    hr: "Dodaj projekt kolonizacije",
    cs: "Přidat projekt kolonizace",
    da: "Tilføj koloniseringsprojekt",
    nl: "Kolonisatieproject toevoegen",
    fi: "Lisää kolonisaatiohanke",
    fr: "Ajouter un projet de colonisation",
    de: "Kolonisierungsprojekt hinzufügen",
    el: "Προσθήκη έργου αποικισμού",
    hi: "उपनिवेश परियोजना जोड़ें",
    hu: "Kolonizációs projekt hozzáadása",
    it: "Aggiungi progetto di colonizzazione",
    ja: "植民地化プロジェクトを追加する",
    ko: "식민지화 프로젝트 추가",
    lt: "Pridėti kolonizacijos projektą",
    no: "Legg til koloniseringsprosjekt",
    pl: "Dodaj projekt kolonizacji",
    "pt-BR": "Adicionar projeto de colonização",
    ro: "Adăugați proiectul de colonizare",
    ru: "Добавить проект колонизации",
    "es-ES": "Agregar proyecto de colonización",
    "sv-SE": "Lägg till koloniseringsprojekt",
    th: "เพิ่มโครงการตั้งถิ่นฐาน",
    tr: "Sömürgeleştirme Projesi Ekle",
    uk: "Додати проект колонізації",
  };

  static readonly COLONIZATION_REMOVE_BOT_DESCRIPTION = {
    "en-US": "Remove Colonization Project",
    "en-GB": "Remove Colonization Project",
    bg: "Премахване на проект за колонизация",
    "zh-CN": "删除殖民化项目",
    "zh-TW": "刪除殖民化項目",
    hr: "Ukloni projekt kolonizacije",
    cs: "Odebrat projekt kolonizace",
    da: "Fjern koloniseringsprojekt",
    nl: "Kolonisatieproject verwijderen",
    fi: "Poista kolonisaatiohanke",
    fr: "Supprimer un projet de colonisation",
    de: "Kolonisierungsprojekt entfernen",
    el: "Κατάργηση έργου αποικισμού",
    hi: "उपनिवेश परियोजना हटाएं",
    hu: "Kolonizációs projekt eltávolítása",
    it: "Rimuovi progetto di colonizzazione",
    ja: "植民地化プロジェクトを削除する",
    ko: "식민지화 프로젝트 제거",
    lt: "Pašalinti kolonizacijos projektą",
    no: "Fjern koloniseringsprosjekt",
    pl: "Usuń projekt kolonizacji",
    "pt-BR": "Remover projeto de colonização",
    ro: "Eliminați proiectul de colonizare",
    ru: "Удалить проект колонизации",
    "es-ES": "Eliminar proyecto de colonización",
    "sv-SE": "Ta bort koloniseringsprojekt",
    th: "ลบโครงการตั้งถิ่นฐาน",
    tr: "Sömürgeleştirme Projesini Kaldır",
    uk: "Видалити проект колонізації",
  };

  static readonly COLONIZATION_LEAVE_BOT_DESCRIPTION = {
    "en-US": "Leave Colonization Project",
    "en-GB": "Leave Colonization Project",
    bg: "Напуснете проект за колонизация",
    "zh-CN": "离开殖民化项目",
    "zh-TW": "離開殖民化項目",
    hr: "Napusti projekt kolonizacije",
    cs: "Opustit projekt kolonizace",
    da: "Forlad koloniseringsprojekt",
    nl: "Kolonisatieproject verlaten",
    fi: "Jätä kolonisaatiohanke",
    fr: "Quitter le projet de colonisation",
    de: "Kolonisierungsprojekt verlassen",
    el: "Αφήστε το έργο αποικισμού",
    hi: "उपनिवेश परियोजना छोड़ें",
    hu: "Kolonizációs projekt elhagyása",
    it: "Lascia progetto di colonizzazione",
    ja: "植民地化プロジェクトを離れる",
    ko: "식민지화 프로젝트 떠나기",
    lt: "Palikti kolonizacijos projektą",
    no: "Forlat koloniseringsprosjekt",
    pl: "Opuść projekt kolonizacji",
    "pt-BR": "Sair do projeto de colonização",
    ro: "Părăsiți proiectul de colonizare",
    ru: "Покинуть проект колонизации",
    "es-ES": "Abandonar proyecto de colonización",
    "sv-SE": "Lämna koloniseringsprojekt",
    th: "ออกจากโครงการตั้งถิ่นฐาน",
    tr: "Sömürgeleştirme Projesinden Ayrıl",
    uk: "Покинути проект колонізації",
  };

  static readonly COLONIZATION_LIST_BOT_DESCRIPTION = {
    "en-US": "List Colonization Projects",
    "en-GB": "List Colonization Projects",
    bg: "Списък на проектите за колонизация",
    "zh-CN": "列出殖民化项目",
    "zh-TW": "列出殖民化項目",
    hr: "Popis projekata kolonizacije",
    cs: "Seznam projektů kolonizace",
    da: "Liste over koloniseringsprojekter",
    nl: "Lijst met kolonisatieprojecten",
    fi: "Luettelo kolonisaatiohankkeista",
    fr: "Lister les projets de colonisation",
    de: "Liste der Kolonisierungsprojekte",
    el: "Κατάλογος έργων αποικισμού",
    hi: "उपनिवेश परियोजनाओं की सूची",
    hu: "Kolonizációs projektek listája",
    it: "Elenco dei progetti di colonizzazione",
    ja: "植民地化プロジェクトのリスト",
    ko: "식민지화 프로젝트 목록",
    lt: "Kolonizacijos projektų sąrašas",
    no: "Liste over koloniseringsprosjekter",
    pl: "Lista projektów kolonizacji",
    "pt-BR": "Listar projetos de colonização",
    ro: "Lista proiectelor de colonizare",
    ru: "Список проектов колонизации",
    "es-ES": "Listar proyectos de colonización",
    "sv-SE": "Lista över koloniseringsprojekt",
    th: "รายการโครงการตั้งถิ่นฐาน",
    tr: "Sömürgeleştirme Projelerini Listele",
    uk: "Список проектів колонізації",
  };

  static readonly COLONIZATION_PARTICIPATE_BOT_DESCRIPTION = {
    "en-US": "Participate in Colonization Project",
    "en-GB": "Participate in Colonization Project",
    bg: "Участие в проект за колонизация",
    "zh-CN": "参与殖民化项目",
    "zh-TW": "參與殖民化項目",
    hr: "Sudjelujte u projektu kolonizacije",
    cs: "Účast na projektu kolonizace",
    da: "Deltag i koloniseringsprojekt",
    nl: "Deelname aan kolonisatieproject",
    fi: "Osallistu kolonisaatiohankkeeseen",
    fr: "Participer au projet de colonisation",
    de: "Teilnahme am Kolonisierungsprojekt",
    el: "Συμμετοχή στο έργο αποικισμού",
    hi: "उपनिवेश परियोजना में भाग लें",
    hu: "Vegyen részt a kolonizációs projektben",
    it: "Partecipa al progetto di colonizzazione",
    ja: "植民地化プロジェクトに参加する",
    ko: "식민지화 프로젝트에 참여",
    lt: "Dalyvaukite kolonizacijos projekte",
    no: "Delta i koloniseringsprosjekt",
    pl: "Uczestnicz w projekcie kolonizacji",
    "pt-BR": "Participar do projeto de colonização",
    ro: "Participați la proiectul de colonizare",
    ru: "Участвовать в проекте колонизации",
    "es-ES": "Participar en el proyecto de colonización",
    "sv-SE": "Delta i koloniseringsprojekt",
    th: "เข้าร่วมในโครงการตั้งถิ่นฐาน",
    tr: "Sömürgeleştirme Projesine Katılın",
    uk: "Брати участь у проекті колонізації",
  };

  static readonly COLONIZATION_PROGRESS_BOT_DESCRIPTION = {
    "en-US": "Get Colonization Project Progress",
    "en-GB": "Get Colonization Project Progress",
    bg: "Получаване на напредъка на проекта за колонизация",
    "zh-CN": "获取殖民化项目进展",
    "zh-TW": "獲取殖民化項目進展",
    hr: "Dobiti napredak projekta kolonizacije",
    cs: "Získat pokrok projektu kolonizace",
    da: "Få koloniseringsprojektets fremskridt",
    nl: "Kolonisatieprojectvoortgang ophalen",
    fi: "Hanki kolonisaatiohankkeen edistyminen",
    fr: "Obtenir les progrès du projet de colonisation",
    de: "Fortschritt des Kolonisierungsprojekts abrufen",
    el: "Λήψη προόδου έργου αποικισμού",
    hi: "उपनिवेश परियोजना प्रगति प्राप्त करें",
    hu: "Rendszerkolonizációs projekt előrehaladásának lekérése",
    it: "Ottieni i progressi del progetto di colonizzazione",
    ja: "植民地化プロジェクトの進捗を取得する",
    ko: "식민지화 프로젝트 진행 상황 가져 오기",
    lt: "Gauti kolonizacijos projekto pažangą",
    no: "Få koloniseringsprosjektets fremgang",
    pl: "Pobierz postępy projektu kolonizacji",
    "pt-BR": "Obter progresso do projeto de colonização",
    ro: "Obțineți progresul proiectului de colonizare",
    ru: "Получить прогресс проекта колонизации",
    "es-ES": "Obtener el progreso del proyecto de colonización",
    "sv-SE": "Hämta koloniseringsprojektets framsteg",
    th: "รับความคืบหน้าของโครงการตั้งถิ่นฐาน",
    tr: "Sömürgeleştirme Projesi İlerlemesini Alın",
    uk: "Отримати прогрес проекту колонізації",
  };

  static readonly COLONIZATION_UPDATE_PROGRESS_BOT_DESCRIPTION = {
    "en-US": "Update Colonization Project Progress",
    "en-GB": "Update Colonization Project Progress",
    bg: "Актуализиране на напредъка на проекта за колонизация",
    "zh-CN": "更新殖民化项目进展",
    "zh-TW": "更新殖民化項目進展",
    hr: "Ažurirajte napredak projekta kolonizacije",
    cs: "Aktualizovat pokrok projektu kolonizace",
    da: "Opdater koloniseringsprojektets fremskridt",
    nl: "Kolonisatieprojectvoortgang bijwerken",
    fi: "Päivitä kolonisaatiohankkeen edistyminen",
    fr: "Mettre à jour les progrès du projet de colonisation",
    de: "Aktualisieren Sie den Fortschritt des Kolonisierungsprojekts",
    el: "Ενημέρωση προόδου έργου αποικισμού",
    hi: "उपनिवेश परियोजना प्रगति अपडेट करें",
    hu: "Frissítse a kolonizációs projekt előrehaladását",
    it: "Aggiorna i progressi del progetto di colonizzazione",
    ja: "植民地化プロジェクトの進捗を更新する",
    ko: "식민지화 프로젝트 진행 상황 업데이트",
    lt: "Atnaujinkite kolonizacijos projekto pažangą",
    no: "Oppdater koloniseringsprosjektets fremgang",
    pl: "Zaktualizuj postępy projektu kolonizacji",
    "pt-BR": "Atualizar o progresso do projeto de colonização",
    ro: "Actualizați progresul proiectului de colonizare",
    ru: "Обновить прогресс проекта колонизации",
    "es-ES": "Actualizar el progreso del proyecto de colonización",
    "sv-SE": "Uppdatera koloniseringsprojektets framsteg",
    th: "อัปเดตความคืบหน้าของโครงการตั้งถิ่นฐาน",
    tr: "Sömürgeleştirme Projesi İlerlemesini Güncelle",
    uk: "Оновити прогрес проекту колонізації",
  };
}
